### PR TITLE
App specs

### PR DESCRIPTION
**Pull request by Arcanemagus**
Most of these specs are commented out due to issues with the initialization of the tests, to be fixed later.

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-pylint/89)

### CODE REVIEW

**Comment by SpainTrain** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[spec/linter-pylint-spec.js, line 2 \[r1\]](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89#-K3ap-dAPuHkq10Tky55:-K3ap-dAPuHkq10Tky56:2124692905) ([raw file](https://github.com/atomlinter/linter-pylint/blob/62104153fca43c33b2a0df20e93ef4e20cefc7ca/spec/linter-pylint-spec.js#L2)):_
FYI placing an `.eslintrc` file in this dir with this stuff might be a DRYer approach

---

_[spec/linter-pylint-spec.js, line 9 \[r1\]](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89#-K3ap8vPqzj19TDKcVFc:-K3ap8vPqzj19TDKcVFd:-1214409652) ([raw file](https://github.com/atomlinter/linter-pylint/blob/62104153fca43c33b2a0df20e93ef4e20cefc7ca/spec/linter-pylint-spec.js#L9)):_
is this promise-returning?  Does it need to be returned?

---

_[spec/linter-pylint-spec.js, line 25 \[r1\]](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89#-K3apNYbiQX6aMzO-yTX:-K3apNYbiQX6aMzO-yTY:1677992419) ([raw file](https://github.com/atomlinter/linter-pylint/blob/62104153fca43c33b2a0df20e93ef4e20cefc7ca/spec/linter-pylint-spec.js#L25)):_
Should we create an issue so we remember to come back and fix =-D

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89)_

**Comment by Arcanemagus** [comment]
Wow, Reviewable doesn't put line comments back here? That's annoying.

**Comment by steelbrain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[spec/linter-pylint-spec.js, line 9 \[r1\]](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89#-K3ap8vPqzj19TDKcVFc:-K3aq21CDjqsI0LlBKM3:2136659147) ([raw file](https://github.com/atomlinter/linter-pylint/blob/62104153fca43c33b2a0df20e93ef4e20cefc7ca/spec/linter-pylint-spec.js#L9)):_
`atom.packages.activatePackage` returns a promise

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89)_

**Comment by SpainTrain** [comment]
> Reviewable doesn't put line comments back here?

No, because revisions in reviewable survive even in the face of rebasing, so there is no 1:1 mapping between gh and reviewable

**Comment by Arcanemagus** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[spec/linter-pylint-spec.js, line 2 \[r1\]](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89#-K3ap-dAPuHkq10Tky55:-K3aqOOHSJHBDlkI73JR:-682275779) ([raw file](https://github.com/atomlinter/linter-pylint/blob/62104153fca43c33b2a0df20e93ef4e20cefc7ca/spec/linter-pylint-spec.js#L2)):_
Sounds good to me.

---

_[spec/linter-pylint-spec.js, line 25 \[r1\]](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89#-K3apNYbiQX6aMzO-yTX:-K3aqdLHTrWWte2S9QUG:-1504763431) ([raw file](https://github.com/atomlinter/linter-pylint/blob/62104153fca43c33b2a0df20e93ef4e20cefc7ca/spec/linter-pylint-spec.js#L25)):_
Good idea.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89)_

**Comment by SpainTrain** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[spec/linter-pylint-spec.js, line 9 \[r1\]](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89#-K3ap8vPqzj19TDKcVFc:-K3aq_SH6DVJsNpinkI5:-1625193176) ([raw file](https://github.com/atomlinter/linter-pylint/blob/62104153fca43c33b2a0df20e93ef4e20cefc7ca/spec/linter-pylint-spec.js#L9)):_
so needs to be like?

```js
return waitsForPromise(() => {
    return Promise.all([
        atom.packages.activatePackage('linter-pylint'),
        atom.packages.activatePackage('language-python').then(() =>
            atom.workspace.open(__dirname + '/files/good.py')
    ]);
})
```

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89)_

**Comment by SpainTrain** [comment]
Reviewed 1 of 2 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89)_

**Comment by steelbrain** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec/linter-pylint-spec.js, line 9 \[r1\]](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89#-K3ap8vPqzj19TDKcVFc:-K3arOQxPWWvxogY1EUt:-980734083) ([raw file](https://github.com/atomlinter/linter-pylint/blob/62104153fca43c33b2a0df20e93ef4e20cefc7ca/spec/linter-pylint-spec.js#L9)):_
Yep, that's what it should be

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89)_

**Comment by SpainTrain** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89)_

**Comment by Arcanemagus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[spec/linter-pylint-spec.js, line 9 \[r1\]](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89#-K3ap8vPqzj19TDKcVFc:-K3at1slNDYWczbQqUOr:-734232405) ([raw file](https://github.com/atomlinter/linter-pylint/blob/62104153fca43c33b2a0df20e93ef4e20cefc7ca/spec/linter-pylint-spec.js#L9)):_
I'll push that up there, but that doesn't make a difference in the specs being broken unfortunately.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atomlinter/linter-pylint/89)_

**Pull request merged**
