### PR TITLE
Update package dependencies

### PR DESCRIPTION
**Pull request by Arcanemagus**
Should provide better error checking and reporting from `atom-linter` and simpler package dependency installation from `atom-package-deps`.

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-pylint/88)

### CODE REVIEW

**Comment by SpainTrain** [comment]
looks like we just need an empty `spec.coffee` file to get CI passing

**Comment by Arcanemagus** [comment]
Well, proper specs (even basic ones) would be better, but that is one solution.

Any objection to merging this and pushing out a patch release? This should fix #78, or at the very least expose the real issue better.

**Comment by SpainTrain** [comment]
lol, naturally actually having the tests are better, but can just stick the file there to get the build passing for now.  IMO anything merged to master to be green on CI.

**Comment by SpainTrain** [comment]
> Well, proper specs (even basic ones) would be better

**Comment by Arcanemagus** [comment]
Okay, I'll push some basic specs up in a separate PR and then rebase this.

**Pull request merged**
